services:
  nginx:
    image: ghcr.io/thelovinator1/nginx:master
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "80:80/udp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - logs:/var/log/nginx
      - config:/etc/nginx/
      - data:/var/www
volumes:
  logs:
  config:
  data:
